pipeline:
  identifier: Build_harnessdemotest_1684983972850
  name: Build harnessdemotest
  orgIdentifier: default
  projectIdentifier: Test_Demo_Project
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: onpremise
                    repo: nginx
                    tags:
                      - "#nginx"
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1684982785778
        repoName: CI
        build: <+input>
